### ISSUE TITLE
Step through McCord version of Asterisk-k8s, so we can assess what containers we need to create

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/vnf-asterisk#16]
Have a vanilla k8s deploy going via playbook. Includes a variety of CNI plugins (flannel, weave, or Multus), playbooks @ https://github.com/dougbtv/kube-centos-ansible
Also, blog articles for using those playbooks @
k8s 1.5 w/ CNI - http://dougbtv.com/nfvpe/2017/02/16/kubernetes-1.5-centos/
Multus CNI - http://dougbtv.com/nfvpe/2017/02/22/multus-cni/

Generally have sean's version running – but without a few key components due to the fact that this setup is biased towards GCE. D'oh. But.... Extreeeemely valuable resource here.
Still in the process of dissecting it. Notes below, open in text mode if you want, cause they were written in markdown.
—
 
Trying Sean's asterisk k8s
 
Just give it a whirl!
 
```
[centos@kube-master ~]$ git clone https://github.com/dougbtv/sean-k8s-asterisk.git
[centos@kube-master ~]$ cd sean-k8s-asterisk/
[centos@kube-master k8s]$ kubectl create -f 01-nats.yaml 
service "nats" created
deployment "nats" created
[centos@kube-master k8s]$ kubectl create -f app.yaml 
deployment "app" created
[centos@kube-master k8s]$ kubectl create -f asterisk.yaml 
service "asterisk" created
deployment "asterisk" created
[centos@kube-master k8s]$ kubectl create -f kamailio.yaml 
service "kamailio" created
daemonset "kamailio" created
```
 
Until it doesn't whirl.
 
```
[centos@kube-master k8s]$  kubectl get pods 
NAME                        READY     STATUS             RESTARTS   AGE
app-1558292000-gsk9f        1/1       Running            2          17m
asterisk-4113088863-kvkrw   1/3       CrashLoopBackOff   14         17m
nats-4212206518-hxpq1       1/1       Running            0          17m
```
 
Describe looks... fairly big to paste. Here's the culprit, appears.
 
```
[centos@kube-master k8s]$ kubectl logs asterisk-4113088863-kvkrw -c natsgw
t=2017-02-27T21:17:59+0000 lvl=info msg="Starting ari-proxy server"
t=2017-02-27T21:18:01+0000 lvl=eror msg="Failed to connect to NATS" url=nats://10.109.51.206:4222 error="nats: no servers available for connection"
```
 
Lets look at the services...
 
```
[centos@kube-master k8s]$ kubectl get svc
NAME         CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
asterisk     10.98.235.155   <none>        5060/UDP                     18m
kamailio     10.104.182.50   <none>        5060/UDP                     18m
kubernetes   10.96.0.1       <none>        443/TCP                      26m
nats         10.109.51.206   <none>        4222/TCP,6222/TCP,8222/TCP   18m
```
 
I can kinda curl it...
 
```
[centos@kube-master k8s]$ curl 10.109.51.206:4222
INFO {"server_id":"PIySZS1JR6bNmcEZGFvKkz","version":"0.9.4","go":"go1.6.3","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576} 
-ERR 'Unknown Protocol Operation'
-ERR 'Parser Error'
```
 
Looks look ok except for me curling it...
 
```
[centos@kube-master k8s]$ kubectl logs nats-4212206518-hxpq1
[1] 2017/02/27 21:04:22.039812 [INF] Starting nats-server version 0.9.4
[1] 2017/02/27 21:04:22.039888 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2017/02/27 21:04:22.040264 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2017/02/27 21:04:22.040354 [INF] Server is ready
[1] 2017/02/27 21:04:22.040928 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2017/02/27 21:24:05.098637 [ERR] 10.244.0.0:36888 - cid:2 - Error reading from client: Client Parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nUser-Agent: curl"...'
```
 
Was it a timing error / readiness depedency error? Let's try to delete the asterisk pod...
 
```
[centos@kube-master k8s]$ kubectl delete -f asterisk.yaml 
service "asterisk" deleted
deployment "asterisk" deleted
[centos@kube-master k8s]$ watch -n3 kubectl get pods --all-namespaces
[centos@kube-master k8s]$ kubectl create -f asterisk.yaml 
service "asterisk" created
deployment "asterisk" created
```
 
So yeah, the gist is that we need for NATS to be all ready. Likely, this needs a [readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/)
 
Sean is a fucking wizard. Nice work. It worked after that.
 
Next steps are to dissect this and learn from the parts that we want.
 
Things that didn't work so far..
 
Kamailio
 
Apparently this is using a GCE specific parameter, that looks like labelling (to my untrained eyes) kinda to tell it which node has kamailio.
 
As found in the `./live-demo/k8s/kamailio.yaml`
 
```
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-kamailio
```
 
 
—
 
Observations
 
Firstly: This apparently uses GCE. Which might explain some specificity in some of the Dockerfiles in particular.
 
There are 4 pods, and 3 services, defined in 4 yaml files found in `./live-demo/k8s/*.yaml`
 
These pods are named:
 
app
asterisk
nats
 
Here's what the pods and services look like:
 
```
[centos@kube-master k8s]$ kubectl get pods
NAME                        READY     STATUS    RESTARTS   AGE
app-1558292000-gsk9f        1/1       Running   2          16h
asterisk-4113088863-ltlpm   3/3       Running   0          15h
nats-4212206518-hxpq1       1/1       Running   0          16h
 
[centos@kube-master k8s]$ kubectl get svc
NAME         CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
asterisk     10.103.209.162   <none>        5060/UDP                     15h
kamailio     10.104.182.50    <none>        5060/UDP                     16h
kubernetes   10.96.0.1        <none>        443/TCP                      16h
nats         10.109.51.206    <none>        4222/TCP,6222/TCP,8222/TCP   16h
```
 
Kamailio
 
Kamailio config is a beautiful example of using confd.
 
Asterisk
 
The asterisk pod, as defined by `./live-demo/k8s/asterisk.yaml` is three containers:
 
asterisk (cycoresystems/astricon-2016-asterisk:gce)
config (cycoresystems/astricon-2016-asteriskconfig:gce)
natsgw (cycoresystems/astricon-2016-natsgw:gce)
 
Ch-ch-ch-changes, turn and face the strange
 
Time may change me, but I can't change time.
 
Alright, so let's start with Kamailio. Let's label a node and add the [nodeselector constraint](https://kubernetes.io/docs/user-guide/node-selection/).
 
```
[centos@kube-master sean-k8s-asterisk]$ kubectl get nodes
NAME            STATUS         AGE
kube-master     Ready,master   18h
kube-minion-1   Ready          18h
kube-minion-2   Ready          18h
[centos@kube-master sean-k8s-asterisk]$ kubectl label nodes kube-minion-2 voiptype=proxy
node "kube-minion-2" labeled
[centos@kube-master sean-k8s-asterisk]$ kubectl get nodes --show-labels
NAME            STATUS         AGE       LABELS
kube-master     Ready,master   19h       beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubeadm.alpha.kubernetes.io/role=master,kubernetes.io/hostname=kube-master
kube-minion-1   Ready          18h       beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=kube-minion-1
kube-minion-2   Ready          18h       beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=kube-minion-2,voiptype=proxy
```
 
Now, let's change the constraint in the kamailio yaml
 
```
$ git diff live-demo/k8s/kamailio.yaml
       nodeSelector:
       cloud.google.com/gke-nodepool: pool-kamailio
+        voiptype: proxy
```
 
And I went and deleted/created it, and.... asterisk pod is choking? And I don't see that damn kamailio pod.
 
Deleting asterisk pod... Had to do that a few times. Thinking there's some kinda race condition or something? Unsure. At any rate, Asterisk comes up after a few restarts.
 
Now kamailio already exists. I delete it and then watch...
 
...Asterisk pod goes haywire.
 
Where the frig is the Kamailio pod?
 
What's the error? Ok, it's the `config` container.
 
```
  1m    55s 2   {kubelet kube-minion-2}             Warning FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "config" with CrashLoopBackOff: "Back-off 20s restarting failed container=config pod=asterisk-4113088863-32sl9_default(6e3fc0f3-fdd3-11e6-9f03-5254000a2fae)"
 
```
 
Does this have something to do with the volume named "config"? That appears to at least be named the same between the two, if not the same volume.
 
Oh, did you know you can describe a daemonset? You can.
 
```
[centos@kube-master k8s]$ kubectl describe daemonset kamailio
```
 
Ok, so now that I'm bringing that up in a controlled manner (and my mistake was previously, that I didn't have my fix properly in with my `voiptype: proxy` label nodeselector). Now, there's other issues, let's bring it up again and diagnose it.

I'm going to close this one out, and leave my final assessment in the description. Generally, my assessment is that I've stepped through his version, and I plan to start a little bit smaller. This one relies fairly heavily on configuration parameters gleaned from GCE, and also uses Kamailio & RTPproxy, and I think we can start without those, and add them as they become necessary to our requirements.

**Comment by isaldarriaga** [comment]
This commands worked for me:

```
kubectl label nodes $(kubectl get nodes | grep gke | awk -F ' ' 'NR==1{print $1}') cloud.google.com/gke-nodepool=pool-kamailio --overwrite
kubectl label nodes $(kubectl get nodes | grep gke | awk -F ' ' 'NR==2{print $1}') cloud.google.com/gke-nodepool=pool-kamailio --overwrite
kubectl label nodes $(kubectl get nodes | grep gke | awk -F ' ' 'NR==3{print $1}') cloud.google.com/gke-nodepool=pool-kamailio --overwrite
```

It properly labels the first 3 nodes in a GKE cluster (NR==1, NR==2, NR==3) so the DaemonSet launches the pods in those nodes.

The "kamailio" container in the kamailio-xxx pod is failing though:
```
$ kubectl get po

NAME                            READY     STATUS             RESTARTS   AGE
asterisk-1744660152-8msl9       3/3       Running            13         1d
app-3527931237-jg899   1/1       Running            0          4h
kamailio-t9bjr                  2/3       CrashLoopBackOff   6          10m
```

The error:
```
$ kubectl logs kamailio-t9bjr -c kamailio

2017-08-24T00:18:25Z gke-qphonebook-cluster-default-pool-72561ba1-992g confd[13]: INFO Backend set to env
2017-08-24T00:18:25Z gke-qphonebook-cluster-default-pool-72561ba1-992g confd[13]: INFO Starting confd
2017-08-24T00:18:25Z gke-qphonebook-cluster-default-pool-72561ba1-992g confd[13]: INFO Backend nodes set to 
2017-08-24T00:18:25Z gke-qphonebook-cluster-default-pool-72561ba1-992g confd[13]: INFO /etc/kamailio/kamailio.cfg has md5sum 17481ad2235ef9698da57c6e90d5ac2b should be 469d897d2dde81f6320357a41712c89f
2017-08-24T00:18:25Z gke-qphonebook-cluster-default-pool-72561ba1-992g confd[13]: INFO Target config /etc/kamailio/kamailio.cfg out of sync
2017-08-24T00:18:25Z gke-qphonebook-cluster-default-pool-72561ba1-992g confd[13]: INFO Target config /etc/kamailio/kamailio.cfg has been updated
 0(1) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 35, column 68-74: syntax error
 0(1) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 35, column 68-74: invalid host or interface name
 0(1) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 35, column 75: 
ERROR: bad config file (3 errors)
```
Looks like the software expects a specific checksum on the configuration file, then replace it and fails with the default values.

Any idea?

**Comment by dougbtv** [comment]
Hrmmm, that doesn't look like a kamailio running for vnf asterisk, as the
only kamailio instance is for Homer. Do you have the yaml resource
definition it's created from, as well as the kamailio config? Looks like a
run of the mill bad config for kamailio.

**Comment by dougbtv** [comment]
secondary comment, didn't realize which issue this was posted on.... now I realize it's the trial with Sean's. Unfortunately, since I don't use GKE, I gave up on it, and was using vanilla k8s. Sorry I don't have more info! I noticed Sean replied to you on his issue, though.

**Comment by juansalvatella** [comment]
@isaldarriaga I stumbled upon this very same issue and Sean helped me troubleshoot it! The problem is that GKE generates a public hostname that includes the word “default” which Kamailio doesnt like it. You can edit the kamailio.cfg and remove the hostname parameter. It should work then.
