### ISSUE TITLE
Create automated deployment of Asterisk to Virtual Machines so that we can mock up virtualized deployment to later use as basis for Docker containers

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/vnf-asterisk#22]
This is probably taking the info done earlier and building a VM image (qcow2?) that can easily instantiate an Asterisk component. Snapshot a manual deploy? Use DIB?

**Comment by leifmadsen** [comment]
I have infrastructure deployment done now via TOAD (baremetal). Documentation will come from that (some is already done). I am in the process of automating the deployments documented here:

https://github.com/leifmadsen/vnf-asterisk/blob/master/notes/compiling_asterisk.md

This is being done via Ansible.

**Comment by leifmadsen** [comment]
No longer needed for post-AstriCon 2017. All containers, all the time baby!
